name: CloudStore CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Make Maven wrappers executable
        run: |
          chmod +x product-service/mvnw
          chmod +x user-order-service/mvnw

      - name: Test product-service
        working-directory: product-service
        run: ./mvnw test

      - name: Test user-order-service
        working-directory: user-order-service
        run: ./mvnw test

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build product-service Docker image
        run: docker build -t ali456663/cloudstore-product-service:latest ./product-service

      - name: Build user-order-service Docker image
        run: docker build -t ali456663/cloudstore-user-order-service:latest ./user-order-service

      - name: Push product-service Docker image
        if: github.event_name == 'push'
        run: docker push ali456663/cloudstore-product-service:latest

      - name: Push user-order-service Docker image
        if: github.event_name == 'push'
        run: docker push ali456663/cloudstore-user-order-service:latest
